#!/bin/bash

#this hook is responsible for asking the developer if they would like to push their code to github. 

set -e

exec < /dev/tty
echo "POST COMMIT" 

#getting user's decision on wanted to push their code
CURRENT_BRANCH=$(git symbolic-ref --short HEAD)

read -p 'would you like to push your code? yes/no: ' PUSH_DECISION
echo ${PUSH_DECISION}

if [[ $PUSH_DECISION = 'yes' ]]
then
    echo $(git push -u origin "${CURRENT_BRANCH}")
    exit 0
elif [[ $PUSH_DECISION = 'no' ]]
then
    echo 'ok have a good day'
    exit 1
fi