#!/bin/bash

#this git hook is responsible for running a linter and checking the code quality.
set -e
echo "PRE-COMMIT"

deno lint --unstable

echo $?
# currentValue=$?
# echo ${currentValue}
# if $currentValue -ne 0
# then
#     exit 1
# fi

# exit 1
